### ISSUE TITLE
Multiple characters appear at the same time in <script> tag

### ISSUE THREAD

**Issue by albacoretuna** [writeas/htmlhouse#1]
Hello, thank you for the awesome product you have open sourced. 

After installing, I'm having some problems with the editor. Characters start to appear multitimes. 
So I'm typing <script> and suddenly it becomes <asssssdcccccrrrrripp>>>>> 

Anyone experienced that? 
I tested on chrome and firefox, on ubuntu. The console gets full of errors like this: 

```
VM2586:1 Uncaught SyntaxError: Invalid or unexpected tokenglobalEval @ jquery-2.1.4.min.js:2domManip @ jquery-2.1.4.min.js:3append @ jquery-2.1.4.min.js:3(anonymous function) @ jquery-2.1.4.min.js:3n.access @ jquery-2.1.4.min.js:2html @ jquery-2.1.4.min.js:3updatePreview @ wmfyogfj.html:87r._signal @ ace.js:1onChange @ ace.js:1r._signal @ ace.js:1applyDelta @ ace.js:1insertMergedLines @ ace.js:1insert @ ace.js:1insert @ ace.js:1insert @ ace.js:1exec @ ace.js:1(anonymous function) @ ace.js:1r._emit.r._dispatchEvent @ ace.js:1exec @ ace.js:1onTextInput @ ace.js:1onTextInput @ ace.js:1A @ ace.js:1O @ ace.js:1
VM2587:2 Uncaught SyntaxError: Invalid or unexpected tokenglobalEval @ jquery-2.1.4.min.js:2domManip @ jquery-2.1.4.min.js:3append @ jquery-2.1.4.min.js:3(anonymous function) @ jquery-2.1.4.min.js:3n.access @ jquery-2.1.4.min.js:2html @ jquery-2.1.4.min.js:3updatePreview @ wmfyogfj.html:87r._signal @ ace.js:1onChange @ ace.js:1r._signal @ ace.js:1applyDelta @ ace.js:1insertMergedLines @ ace.js:1insert @ ace.js:1insert @ ace.js:1insert @ ace.js:1exec @ ace.js:1(anonymous function) @ ace.js:1r._emit.r._dispatchEvent @ ace.js:1exec @ ace.js:1onTextInput @ ace.js:1onTextInput @ ace.js:1A @ ace.js:1O @ ace.js:1
```

**Comment by thebaer** [comment]
Hi, are you writing JavaScript into the editor? This has been known to mess up the editor a bit. Or is it occurring even without writing any JS?

**Comment by albacoretuna** [comment]
Yes starts with adding JavaScript

**Comment by albacoretuna** [comment]
Is there an easy way to add a separate window for JavaScript?

**Comment by thebaer** [comment]
It's not set up for this at the moment, but that's definitely what we should do. If you (or anyone) are interested in helping with this, you can [join #htmlhouse in our Slack channel](http://slack.write.as/) and we can figure out a solution.

Otherwise we have some other priorities at the moment and I'll have to think about this a bit, so for now the best workaround might be pasting a `script` tag into your page that points to an external script, like `<script src="https://..."></script>`.

**Comment by christiangenco** [comment]
I have a quick fix: just surround `$view.contents().find("body").html(val)` in [/templates/editor.html](https://github.com/writeas/htmlhouse/blob/0ab4c7fc437cb61004772a8f085ddfb711b072b9/templates/editor.html) with a try catch:

```javascript
try {
  $view.contents().find("body").html(val);
} catch (err) {
  console.error(err);
}
```

It's not ideal because if you have a `<script>` tag with an error in it, jQuery will try to evaluate it when you call `.html()`, it'll get caught, and the view won't be updated. Ergo, if you have a javascript error anywhere in your html, the preview won't update.

A workaround for that might be to show the javascript error (the `err` caught in the try catch) in the preview.

I'd submit this as a pull request, but I'm not sure if it's supposed to go in the master or develop branch.

**Comment by christiangenco** [comment]
Something else to consider:

`$view.contents().find("body")[0].innerHTML = val;` will never error out, but also doesn't run javascript.

**Comment by thebaer** [comment]
@christiangenco thanks for looking into this! I'd say a broken preview is preferable over a permanently broken editor, as seems to happen now. So I like the try/catch solution, especially since it'll let us keep the UI simple. If you want to throw up a quick pull request off the `develop` branch, I'll get that merged in and deployed right away.

After that, I agree, there needs to be some visual indication that there are errors. I'll start thinking about that and get it in next.

**Comment by thebaer** [comment]
Worked great -- the fix is live now. Thanks again for the help @christiangenco!
